code_tutors/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from tutorials import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('log_in/', views.LogInView.as_view(), name='log_in'),
    path('log_out/', views.log_out, name='log_out'),
    path('password/', views.PasswordView.as_view(), name='password'),
    path('profile/', views.ProfileUpdateView.as_view(), name='profile'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    # Tutor views
    path('tutors/', views.TutorListView.as_view(), name='tutor_list_view'),
    path('update_schedule/', views.TutorAvailabilityUpdateView.as_view(), name='update_schedule'),
     # Student views
    path('lesson_requests/create/', views.create_lesson_request, name='create_lesson_request'),
    path('lesson_requests/view/', views.student_view_requests, name='student_view_requests'),
    path('student_view_invoices/', views.student_view_invoices, name='student_view_invoices'),
    # Admin views
    path('lesson_requests/admin/', views.admin_view_requests, name='admin_view_requests'),
    path('lesson_requests/<int:pk>/update-status/', views.update_request_status, name='update_request_status'),
    path('cancel_lesson/<int:lesson_id>/', views.cancel_lesson, name='cancel_lesson'),
    path('toggle-invoice-paid/<int:invoice_id>/', views.toggle_invoice_paid, name='toggle_invoice_paid'),
    path('generate_invoice/<int:lesson_request_id>/', views.generate_invoice, name='generate_invoice'),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scheduler/urls.py
#urls.py here is to make views in this app accesible

from django.urls import path
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_lesson, name='create-lesson'),
]

tutorials/models.py
from datetime import datetime
from django.utils.timezone import make_aware
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import now
from django.core.validators import MinValueValidator
from decimal import Decimal
from libgravatar import Gravatar
from code_tutors import settings


class User(AbstractUser):
    """Model used for user authentication, and team member related information."""

    username = models.CharField(
        max_length=30,
        unique=True,
        validators=[RegexValidator(
            regex=r'^@\w{3,}$',
            message='Username must consist of @ followed by at least three alphanumericals'
        )]
    )
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    email = models.EmailField(unique=True, blank=False)

    ROLE_CHOICES = [
        ('admin', 'Admin'),
        ('tutor', 'Tutor'),
        ('student', 'Student'),
    ]

    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default='student',
        verbose_name='Role'
    )

    class Meta:
        """Model options."""

        ordering = ['last_name', 'first_name']

    def full_name(self):
        """Return a string containing the user's full name."""

        return f'{self.first_name} {self.last_name}'

    def gravatar(self, size=120):
        """Return a URL to the user's gravatar."""

        gravatar_object = Gravatar(self.email)
        gravatar_url = gravatar_object.get_image(size=size, default='mp')
        return gravatar_url

    def mini_gravatar(self):
        """Return a URL to a miniature version of the user's gravatar."""
        
        return self.gravatar(size=60)


class Tutor(models.Model):
    """Model for tutors, extending User"""

    TOPICS = [
        ('Python', 'Python'),
        ('Java', 'Java'),
        ('C++', 'C++'),
        ('Scala', 'Scala'),
        ('R', 'R'),
        ('Javascript', 'Javascript'),
        ('Swift', 'Swift'),
        ('Go', 'Go'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='tutor_profile')

    subjects = models.CharField(max_length=50, choices=TOPICS, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} - {self.subjects}'


class Student(models.Model):
    """Model for students, extending User"""

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student_profile')
    tutor = models.ForeignKey('Tutor', related_name='students',
                              on_delete=models.SET_NULL, null = True, blank = True)

    def __str__(self):
        return f"{self.user.username}"


class Schedule(models.Model):
    DAYS_OF_WEEK = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    user = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='schedules',
                            null=False,
                            blank=False)
    
    day_of_week = models.CharField(max_length=10, choices=DAYS_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"{self.user.username}: {self.day_of_week} {self.start_time}-{self.end_time}"
    
    def clean(self):
        if self.start_time > self.end_time:
            raise ValidationError("Start time cannot be after end time.")
    
    def save(self, *args, **kwargs):
        # Filter for overlapping schedules for the same user and same day
        overlapping_schedules = Schedule.objects.filter(
            user=self.user,  # Restrict to the same user
            day_of_week=self.day_of_week  # Restrict to the same day
        ).exclude(id=self.id)  # Exclude the current instance

        # Find overlaps
        overlapping_schedules = [
            schedule for schedule in overlapping_schedules
            if schedule.start_time <= self.end_time and schedule.end_time >= self.start_time
        ]

        if overlapping_schedules:
            # Adjust the start and end time to encompass all overlaps
            for schedule in overlapping_schedules:
                self.start_time = min(self.start_time, schedule.start_time)
                self.end_time = max(self.end_time, schedule.end_time)
                # Delete the overlapping schedules
                schedule.delete()

        #save new shcedule
        super().save(*args, **kwargs)


User = get_user_model()

class LessonRequest(models.Model):
    LANGUAGE_CHOICES = [
        ('Python', 'Python'),
        ('Java', 'Java'),
        ('C++', 'C++'),
        ('Scala', 'Scala'),
        ('R', 'R'),
        ('Javascript', 'Javascript'),
        ('Swift', 'Swift'),
        ('Go', 'Go'),
    ]

    TERM_CHOICES = [
        ('Sept-Christmas', 'Sept-Christmas'),
        ('Jan-Easter', 'Jan-Easter'),
        ('March-June', 'March-June'),
    ]

    DAY_CHOICES = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    FREQUENCY_CHOICES = [
        ('Weekly', 'Weekly'),
        ('Bi-Weekly', 'Bi-Weekly'),
        ('Monthly', 'Monthly'),
    ]

    DURATION_CHOICES = [
        (60, '60 minutes'),
        (120, '120 minutes'),
    ]

    student_id = models.ForeignKey('tutorials.User', on_delete=models.CASCADE, related_name='lesson_requests_as_student')
    tutor_id = models.ForeignKey('tutorials.User', on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name='lesson_requests_as_tutor')
    language = models.CharField(max_length=50, choices=LANGUAGE_CHOICES)
    term = models.CharField(max_length=20, choices=TERM_CHOICES)
    day_of_the_week = models.CharField(max_length=10, choices=DAY_CHOICES)
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)
    duration = models.IntegerField(choices=DURATION_CHOICES)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, default='Unallocated')
    date_created = models.DateTimeField(default=now)

    def __str__(self):
        return f"Request by {self.student_id} for {self.language}"


class AllocatedLesson(models.Model):
    LANGUAGE_CHOICES = [
        ('Python', 'Python'),
        ('Java', 'Java'),
        ('C++', 'C++'),
        ('Scala', 'Scala'),
        ('R', 'R'),
        ('Javascript', 'Javascript'),
        ('Swift', 'Swift'),
        ('Go', 'Go'),
    ]

    lesson_request = models.ForeignKey(
        'LessonRequest',
        on_delete=models.CASCADE,
        related_name='allocated_lessons'
    )
    occurrence = models.PositiveIntegerField()
    date = models.DateField()
    time = models.TimeField()
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=100)
    student_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='allocated_lessons_as_student'  # Custom related_name to avoid conflict
    )
    tutor_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='allocated_lessons_as_tutor'  # Custom related_name to avoid conflict
    )

    class Meta:
        unique_together = ('lesson_request', 'occurrence')

    def __str__(self):
        return f"Lesson Request {self.lesson_request.id} - Occurrence {self.occurrence} on {self.date}"

    def clean(self):
        """
        Ensures that the allocated lesson's date is within the lesson request's constraints.
        """
        lesson_datetime = make_aware(datetime.combine(self.date, self.time))
        if lesson_datetime < now():
            raise ValidationError("Allocated lesson date cannot be in the past.")
        super().clean()


class Invoice(models.Model):
    lesson_request = models.ForeignKey(LessonRequest, on_delete=models.CASCADE, related_name='invoice', null=True, blank=True)
    amount = models.DecimalField(max_digits=6, decimal_places=2, default=0, validators=[MinValueValidator(Decimal('0.01'))])
    is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

tutorials/forms.py
"""Forms for the tutorials app."""
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from .models import User, Invoice, LessonRequest
from django.core.exceptions import ValidationError
from .models import User, Schedule

class LogInForm(forms.Form):
    """Form enabling registered users to log in."""

    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

    def get_user(self):
        """Returns authenticated user if possible."""

        user = None
        if self.is_valid():
            username = self.cleaned_data.get('username')
            password = self.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
        return user


class UserForm(forms.ModelForm):
    """Form to update user profiles."""

    class Meta:
        """Form options."""

        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'role']


class NewPasswordMixin(forms.Form):
    """Form mixing for new_password and password_confirmation fields."""

    new_password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(),
        validators=[RegexValidator(
            regex=r'^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).*$',
            message='Password must contain an uppercase character, a lowercase '
                    'character and a number'
            )]
    )
    password_confirmation = forms.CharField(label='Password confirmation', widget=forms.PasswordInput())

    def clean(self):
        """Form mixing for new_password and password_confirmation fields."""

        super().clean()
        new_password = self.cleaned_data.get('new_password')
        password_confirmation = self.cleaned_data.get('password_confirmation')
        if new_password != password_confirmation:
            self.add_error('password_confirmation', 'Confirmation does not match password.')


class PasswordForm(NewPasswordMixin):
    """Form enabling users to change their password."""

    password = forms.CharField(label='Current password', widget=forms.PasswordInput())

    def __init__(self, user=None, **kwargs):
        """Construct new form instance with a user instance."""
        
        super().__init__(**kwargs)
        self.user = user

    def clean(self):
        """Clean the data and generate messages for any errors."""

        super().clean()
        password = self.cleaned_data.get('password')
        if self.user is not None:
            user = authenticate(username=self.user.username, password=password)
        else:
            user = None
        if user is None:
            self.add_error('password', "Password is invalid")

    def save(self):
        """Save the user's new password."""

        new_password = self.cleaned_data['new_password']
        if self.user is not None:
            self.user.set_password(new_password)
            self.user.save()
        return self.user


class SignUpForm(NewPasswordMixin, forms.ModelForm):
    """Form enabling unregistered users to sign up."""

    ROLE_CHOICES = [
        ('student', 'Student'),
        ('tutor', 'Tutor'),
    ]

    role = forms.ChoiceField(choices=ROLE_CHOICES)

    class Meta:
        """Form options."""

        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'role']

    def save(self):
        """Create a new user."""

        super().save(commit=False)
        user = User.objects.create_user(
            self.cleaned_data.get('username'),
            first_name=self.cleaned_data.get('first_name'),
            last_name=self.cleaned_data.get('last_name'),
            email=self.cleaned_data.get('email'),
            role=self.cleaned_data.get('role'),
            password=self.cleaned_data.get('new_password'),
        )
        return user


User = get_user_model()

class LessonRequestForm(forms.ModelForm):
    class Meta:
        model = LessonRequest
        fields = [
            'language', 'term', 'day_of_the_week', 'frequency',
            'duration', 'description', 'tutor_id'
        ]
        widgets = {
            'language': forms.Select(attrs={'class': 'form-control'}),
            'term': forms.Select(attrs={'class': 'form-control'}),
            'day_of_the_week': forms.Select(attrs={'class': 'form-control'}),
            'frequency': forms.Select(attrs={'class': 'form-control'}),
            'duration': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Provide additional details (optional)',
                'maxlength': '1000',
            }),
            'tutor_id': forms.Select(
                attrs={'class': 'form-control', 'placeholder': 'Select a preferred tutor (optional)'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Filter tutors for the dropdown
        self.fields['tutor_id'].queryset = User.objects.filter(role="tutor")
        self.fields['description'].required = False  # Optional
        self.fields['tutor_id'].required = False  # Optional

    def clean_tutor_id(self):
        tutor = self.cleaned_data.get('tutor_id')
        if tutor and tutor.role != "tutor":
            raise ValidationError("Selected user is not a tutor.")
        return tutor

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description and len(description) > 1000:
            raise forms.ValidationError("Description cannot exceed 1000 characters.")
        return description
    

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['day_of_week', 'start_time', 'end_time']
        widgets = {
            'start_time': forms.Select(choices=[(f"{h}:00", f"{h}:00") for h in range(8, 20)], attrs={'class': 'form-control'}),
            'end_time': forms.Select(choices=[(f"{h}:00", f"{h}:00") for h in range(9, 21)], attrs={'class': 'form-control'}),
            'day_of_week': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if start_time and end_time and start_time >= end_time:
            self.add_error('start_time', 'Start Time cannot be before End Time')

        return cleaned_data


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ['lesson_request', 'is_paid', 'amount']
        widgets = {
            'lesson_request': forms.HiddenInput(),
            'is_paid': forms.CheckboxInput(),
        }

tutorials/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <link href="{% static 'custom.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Task Manager</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
  </body>
</html>

tutorials/templates/dashboard.html
{% extends 'base_content.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Welcome to your dashboard {{ user.first_name }} {{ user.last_name }}</h1>
      {% if user.role == 'admin' %}
          <h2>Admin Dashboard</h2>
          <div class="mt-3">
              <a href="{% url 'admin_view_requests' %}" class="btn btn-primary">View All Submitted Requests</a>
              <a href="{% url 'tutor_list_view' %}" class="btn btn-primary">View Tutor List</a>
          </div>
          
      {% elif user.role == 'tutor' %}
        <h2>Tutor Dashboard</h2>
        <div class="mt-3">
          <a href="{% url 'update_schedule' %}" class="btn btn-primary">Update Availability</a>
        </div>
        <div class="mt-5">
          <h3>Your Allocated Lessons</h3>
            {% if allocated_lessons %}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Language</th>
                  <th>Student</th>
                  <th>Description</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for lesson in allocated_lessons %}
                  <tr>
                    <td>{{ lesson.lesson_request.language }}</td>
                    <td>
                      {{ lesson.lesson_request.student_id.first_name }}
                      {{ lesson.lesson_request.student_id.last_name }}
                    </td>
                    <td>{{ lesson.lesson_request.description }}</td>
                    <td>{{ lesson.date|date:"Y-m-d" }}</td>
                    <td>{{ lesson.time|time:"H:i" }}</td>
                      <td>
                          <form method="post" action="{% url 'cancel_lesson' lesson.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Cancel</button>
                          </form>
                      </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <p>You have no allocated lessons at the moment.</p>
          {% endif %}

      </div>
      
      {% elif user.role == 'student' %}
        <h2>Student Dashboard</h2>
        {% if invoice_actions_needed > 0 %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          You have {{ invoice_actions_needed }} unpaid invoices.
        </div>
        {% endif %}
        <div class="mt-3">
          <a href="{% url 'create_lesson_request' %}" class="btn btn-primary">Submit Lesson Request</a>
          <a href="{% url 'student_view_invoices' %}" class="btn btn-primary">
            View your invoices
            {% if invoice_actions_needed > 0 %}
            <span class="badge rounded-pill bg-danger">
              {{ invoice_actions_needed }}
              <span class="visually-hidden">action needed</span>
            </span>
            {% endif %}
          </a>
          <a href="{% url 'student_view_requests' %}" class="btn btn-secondary">View Your Requests</a>
        </div>
        <div class="mt-5">
          <h3>Your Allocated Lessons</h3>
            {% if allocated_lessons %}
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Language</th>
                    <th>Tutor</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for lesson in allocated_lessons %}
                    <tr>
                      <td>{{ lesson.lesson_request.language }}</td>
                      <td>
                        {{ lesson.lesson_request.tutor_id.first_name }}
                        {{ lesson.lesson_request.tutor_id.last_name }}
                      </td>
                      <td>{{ lesson.date|date:"Y-m-d" }}</td>
                      <td>{{ lesson.time|time:"H:i" }}</td>
                        <td>
                            <form method="post" action="{% url 'cancel_lesson' lesson.id %}" style="display:inline;">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger btn-sm">Cancel</button>
                            </form>
                        </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% else %}
              <p>You have no allocated lessons at the moment.</p>
            {% endif %}

        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

tutorials/templates/generate_invoice.html
{% extends "base_content.html" %}
{% block content %}

<div class="container">
    <h2>Generate Invoice for Lesson Request: {{ lesson_request.title }}</h2>
    {% if invoice %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <h3><strong>An invoice already exists for this request, creating a new invoice will delete the existing one.</strong></h3>
        </div>
    {% endif %}
    <p>Description: {{ lesson_request.description}}</p>
    <p>Tutor: {{ lesson_request.preferred_tutor }}</p>
    <p>Student: {{ lesson_request.student }}</p>
    <p>Number of Weeks: {{ lesson_request.no_of_weeks }}</p>

    <h3>Generate Invoice</h3>

    <form action="{% url 'generate_invoice' lesson_request.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="amount">Amount (£):</label>
            <input type="number" step="0.01" name="amount" id="amount" {% if invoice %} value="{{ invoice.amount }}" {% endif %} required>
        </div>

        <div>
            <label for="is_paid">Paid?</label>
            <input type="checkbox" name="is_paid" id="is_paid" {% if invoice %} value="{{ invoice.is_paid }}" {% endif %}>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Create Invoice</button>
        </div>
    </form>

    <a href="{% url 'admin_view_requests' %}" class="btn btn-secondary">Cancel</a>
</div>

{% endblock %}

tutorials/templates/home.html
{% extends 'base.html' %}
{% block body %}
  <div class="container vh-100">
    <div class="row h-100">
      <div class="col-12 my-auto">
        <div class="card cover-card offset-sm-2 offset-md-4 offset-lg-7">
          <h1 class="cover-heading">Task Manager</h1>
          <p class="cover-text">A task manager application by Team <i>Kinkajou</i></p>
          <p>
            <a href='{% url 'sign_up' %}' class="btn btn-lg btn-secondary">
              Sign up
            </a>
          </p>
          <p>
            <a href='{% url 'log_in' %}' class="btn btn-lg btn-secondary">
              Log in
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

tutorials/templates/log_in.html
{% extends 'base_content.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 offset-md-3">
      <h1>Log in</h1>
      <form action="{% url 'log_in' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include 'partials/bootstrap_form.html' with form=form %}
        <input type="submit" value="Log in" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>
{% endblock %}

tutorials/templates/student_dashboard.html
<!-- student_dashboard.html -->
{% extends "base.html" %}

{% block content %}
  <h2>Student Dashboard</h2>
{% endblock %}

tutorials/templates/tutor_dashboard.html
<!-- tutor_dashboard.html -->
{% extends "base.html" %}

{% block content %}
  <h2>Tutor Dashboard</h2>
{% endblock %}

tutorials/templates/tutor_list.html
{% extends 'base_content.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">

            <h1>Available Tutors</h1>

            <!-- Search Form -->
            <form method="GET" action="{% url 'tutor_list_view' %}">
                <label for="subjects">Subject:</label>
                <select id="subjects" name="subjects" class="form-select">
                    <option value="any" {% if request.GET.subjects == "any" or not request.GET.subjects %}selected{% endif %}>Any</option>
                    {% for key, value in subjects %}
                        <option value="{{ key }}" {% if request.GET.subjects == key %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>

                <label for="day">Day:</label>
                <select id="day" name="day" class="form-select">
                    <option value="any" {% if request.GET.day == "any" or not request.GET.day %}selected{% endif %}>Any</option>
                    {% for key, value in days %}
                        <option value="{{ key }}" {% if request.GET.day == key %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>

                <button type="submit" class="btn btn-primary mt-3">Search</button>
            </form>

            <!-- Tutor Table -->
            <h2 class="mt-5">Tutors</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Tutor Name</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Availability</th>
                        <th scope="col">Allocated Lessons</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tutor in tutors %}
                    <tr>
                        <!-- Tutor Name -->
                        <td>{{ tutor.user.first_name }} {{ tutor.user.last_name }}</td>
                        
                        <!-- Subject -->
                        <td>{{ tutor.get_subjects_display }}</td>
                        
                        <!-- Availability -->
                        <td>
                            {% if tutor.availability %}
                                <ul class="list-unstyled">
                                    {% for schedule in tutor.availability %}
                                    <li>{{ schedule.day_of_week }}: {{ schedule.start_time|time:"H:i" }} - {{ schedule.end_time|time:"H:i" }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                Not specified
                            {% endif %}
                        </td>
                        
                        <!-- Allocated Lessons -->
                        <td>
                            {% if tutor.user.allocated_lessons %}
                                <ul class="list-unstyled">
                                    {% for lesson in tutor.user.allocated_lessons %}
                                    <li>{{ lesson.date|date:"D, M j" }} - {{ lesson.time|time:"H:i" }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                No lessons allocated.
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No tutors found matching your criteria.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}